Feature: Ignore Group Commands
taranvohra/bbot-js pull request #14
Opened 2019-10-12 10:54 UTC by oreleraki

Grouped shared commands togther to support 3 new commands and to allow servers with multibots play togther

ignoreGroupCommands [group]

.unignoreGroupCommands [group]

.listGroupCommands

2019-10-13 09:02 UTC, taranvohra requested changes

2019-10-13 09:02 UTC, taranvohra commented on src/commands/genericHandlers.js
> +      message.channel.send('Not enough paramters.');
`return message.channel.send('Not enough parameters.');`   // typo & they can be clubbed together

2019-10-13 09:02 UTC, taranvohra commented on src/commands/genericHandlers.js
> +    store.dispatch(ignoreGroupCommandsAction({ serverId, groupCommands: normalizedProposedGroup }));
local store should be updated after the DB call has gone through

2019-10-13 09:02 UTC, taranvohra commented on src/store/reducers/globals.js
> +		case 'IGNORE_GROUP_COMMANDS':
I feel the name should be `IGNORE_GROUP_COMMAND` (singular) because we are adding it 1 by 1.

2019-10-13 09:02 UTC, taranvohra commented on src/store/reducers/globals.js
> +			if (!state[payload.serverId]) {
redundant. can remove this `if` block

console logs should also be removed

2019-10-13 09:02 UTC, taranvohra commented on src/store/reducers/globals.js
> +		case 'UNIGNORE_GROUP_COMMANDS':
Same singular comment like above. should be `UNIGNORE_GROUP_COMMAND`

2019-10-13 09:02 UTC, taranvohra commented on src/commands/genericHandlers.js
> +      store.dispatch(unignoreGroupCommandsAction({ serverId, groupCommands: normalizedProposedGroup }));
local store should be updated after DB call has gone through

2019-10-13 09:02 UTC, taranvohra commented on src/commands/genericHandlers.js
> +      message.channel.send('Not enough paramters.');
typo and single return message.channel.send(...)

2019-10-13 09:02 UTC, taranvohra commented on src/store/reducers/globals.js
> +	switch (type) {
Add the missing `INIT` case. Have a look at the other reducers and see what they're doing. Whenever the store is being hydrated, for every `discordServer` registered, an `INIT` is being dispatched.

The benefit of this is, it let's you avoid doing things like `if(!state.globals[discordServerId])` because it'll always be there now.

2019-10-13 09:02 UTC, taranvohra commented on src/index.js
> +  if (!state.globals || !state.globals[serverId]) {
redundant `if` condition. Look at my comment on the `INIT` action. `globals` will ALWAYS be there anyway and if `INIT` is handled in the globals reducer, then so will `state.globals[serverId]`

2019-10-13 16:26 UTC, oreleraki commented on src/commands/genericHandlers.js
> +      message.channel.send('Not enough paramters.');
- Gonna fix the type.
- The conditions should not be clubbed the results of them should act diff. the first one should actually not happens and should throw an error or just ignore it if it is protected before.
While the second is specifically of empty parameters.

2019-10-13 16:28 UTC, taranvohra commented on src/commands/genericHandlers.js
> +      message.channel.send('Not enough paramters.');
Oh yeah, I wasn't talking about. I was talking about
```js
if(!proposedGroup) {
    message.channel.send(...); // the return on next line can be merged
   return;
}

2019-10-13 16:30 UTC, oreleraki commented on src/commands/genericHandlers.js
> +    store.dispatch(ignoreGroupCommandsAction({ serverId, groupCommands: normalizedProposedGroup }));
Your right, i was sure i changed as the other procedures. In this case it's also just that it's after the db call.

2019-10-13 16:32 UTC, oreleraki commented on src/store/reducers/globals.js
> +		case 'IGNORE_GROUP_COMMANDS':
I was on the fence on this as well, the naming are usually good but when doing many many relation i'm confusing :)

2019-10-13 16:36 UTC, oreleraki commented on src/store/reducers/globals.js
> +			if (!state[payload.serverId]) {
- Logs will be removed.
- I may not strong in the project and redux yet, but i don't think the condition is redundant. In theory what will happen for the first time this state is fired before any other `state[serverId]` before him, they it will likely fall due to `undefined`. I remember i thought "what will happend" when i wrote it, and it rises as a just case. Do you see it can happen as well or am i over protecting it ?

2019-10-13 16:36 UTC, oreleraki commented on src/commands/genericHandlers.js
> +      store.dispatch(unignoreGroupCommandsAction({ serverId, groupCommands: normalizedProposedGroup }));
As before statement.

2019-10-13 16:37 UTC, oreleraki commented on src/store/reducers/globals.js
> +	switch (type) {
- Oh ok, now i see the point of the earlier command.

2019-10-13 18:10 UTC, oreleraki commented on src/commands/genericHandlers.js
> +      message.channel.send('Not enough paramters.');
Sorry, i ain't following, please give me the line numbers or paste the two conditions.

2019-10-13 18:11 UTC, oreleraki commented on src/commands/genericHandlers.js
> +      message.channel.send('Not enough paramters.');
will fix the type.
And not understand the comment about the single return message.

2019-10-13 18:11 UTC, oreleraki commented on src/index.js
> +  if (!state.globals || !state.globals[serverId]) {
Yup, will add the INIT.

2019-10-14 08:16 UTC, oreleraki reviewed
Fixed.

2019-11-26 15:23 UTC, taranvohra commented
Hey @oreleraki , can you please fix the conflicts? It came up since I merged the `prefix` PR

2019-12-02 15:59 UTC, oreleraki commented
@taranvohra I've rebased and fixed all conflicts.

2019-12-08 12:20 UTC, merged